export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCT_BY_NAME = 'GET_PRODUCT_BY_NAME';
export const GET_PRODUCT_ID = 'GET_PRODUCT_ID';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const FILTER_PRODUCTS_BY_CATEGORY = 'FILTER_PRODUCTS_BY_CATEGORY';
export const FILTER_PRODUCTS_BY_PRICE = 'FILTER_PRODUCTS_BY_PRICE';
export const FILTER_PRODUCTS_BY_BRANDS = 'FILTER_PRODUCTS_BY_BRANDS';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const FILTERS_CLEAR = 'FILTERS_CLEAR ';

