export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCT_BY_NAME = 'GET_PRODUCT_BY_NAME';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const FILTER_PRODUCTS_BY_CATEGORY = 'FILTER_PRODUCTS_BY_CATEGORY'
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

